name: 'Create Release'
description: 'Create a release on Bytebase.'

branding:
  icon: 'database'
  color: 'red'

inputs:
  url:
    description: The bytebase URL.
    required: true
  token:
    description: The Bytebase access token.
    required: true
  project:
    description: 'The project on Bytebase. Format: projects/{project}'
    required: true
  file-pattern:
    description:
      'The file pattern matching migration files. Example: migrations/prod/*.sql'
    required: true

outputs:
  release:
    description:
      'The created release. Format: projects/{project}/release/{release}'

runs:
  using: node20
  main: dist/index.js
